# Generated by Django 5.2.5 on 2025-08-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen_art',
            field=models.ImageField(blank=True, null=True, upload_to='static/articulos_img'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
