# Generated by Django 5.2.5 on 2025-08-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicblog', '0002_articulo_imagen_art_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen_art',
            field=models.ImageField(blank=True, null=True, upload_to='static/articulos_img/'),
        ),
    ]
